theme: jekyll-theme-minimal
title: "MeloMelo: Chat-Stories erzählen. Gemeinsam."
description: "MeloMelo für Lesen und Schreiben interaktiver Chat-Stories / Chat-Storys."
logo: /img/logo2.png
show_downloads: false
plugins:
  - jekyll-seo-tag
