theme: jekyll-theme-minimal
title: "MeloMelo Messenger: Chat-Stories erzählen. Gemeinsam."
description: "MeloMelo ist ein Messenger für das Lesen und Schreiben interaktiver Chat-Stories / Chat-Storys."
logo: /img/logo2.png
show_downloads: false
plugins:
  - jekyll-seo-tag
